stages:
  - unit_tests

variables:
  POSTGRES_USER: 'gfbio_collections'
  POSTGRES_PASSWORD: ''
  POSTGRES_DB: 'test_gfbio_collections'
  POSTGRES_HOST_AUTH_METHOD: trust
  CELERY_BROKER_URL: 'redis://redis:6379/0'

pytest:
  stage: unit_tests
#  image: docker/compose:latest # :1.29.2
  before_script:
    - PATH=$PATH:/home/gitlab-runner/.local/bin
    - docker info
    - docker-compose -f local.yml build
    - docker-compose -f local.yml run --rm django python manage.py migrate
    - docker-compose -f local.yml up -d
  script:
    - docker-compose -f local.yml run django pytest
  tags:
    - collections
