include:
  - project: gfbio/cicd
    file:
      - '.create_merge_request.yml'

variables:
  POSTGRES_USER: 'gfbio_collections'
  POSTGRES_PASSWORD: ''
  POSTGRES_DB: 'test_gfbio_collections'
  POSTGRES_HOST_AUTH_METHOD: trust
  CELERY_BROKER_URL: 'redis://redis:6379/0'

stages:
  - create_merge_request
#  - unit_tests
#  - web_test_check # there is not need to overwrite anything in this stage
#  - tag_release_check

create_merge_request:
  tags:
    - dev-denbi
