variables:
  POSTGRES_USER: 'gfbio_collections'
  POSTGRES_PASSWORD: ''
  POSTGRES_DB: 'test_gfbio_collections'
  POSTGRES_HOST_AUTH_METHOD: trust
  CELERY_BROKER_URL: 'redis://redis:6379/0'

include:
  - project: gfbio/cicd
    file:
      - '.create_merge_request.yml'
      - '.web-test.yml'
      - '.tag_release.yml'

stages:
  - unit_tests
  - create_merge_request
  - web_test_check # there is not need to overwrite anything in this stage
  - tag_release_check

create_merge_request:
  tags:
    - collections-dev

tag_release_check:
  tags:
    - collections-dev

tag_release:
  script:
    - rsync -a /home/gitlab-runner/.envs .
    - docker-compose -f production.yml down
    - docker-compose -f production.yml build
    - docker-compose -f production.yml up -d postgres
    - docker-compose -f production.yml run --rm postgres backup
    - docker-compose -f production.yml run --rm django python manage.py migrate
    - docker-compose -f production.yml run --rm django python manage.py collectstatic
    - docker-compose -f production.yml down
    - docker-compose -f production.yml up -d
  environment:
    name: production
    url: https://collections.rdc.gfbio.dev
  tags:
    - collections-dev
