stages:
  - lint
  - test
  - unit_tests

variables:
  POSTGRES_USER: 'gfbio_collections'
  POSTGRES_PASSWORD: ''
  POSTGRES_DB: 'test_gfbio_collections'
  POSTGRES_HOST_AUTH_METHOD: trust
  CELERY_BROKER_URL: 'redis://redis:6379/0'

flake8:
  stage: lint
  image: python:3.9-alpine
  before_script:
    - whoami
    - ls -la /var/lib/gitlab-runner
    - pip3 install -q flake8
  script:
    - flake8
  tags:
    - collections

pytest:
  stage: test
  image: docker/compose:latest # :1.29.2
#  services:
#    - docker:dind
  before_script:
    - docker info
    - rsync -a /home/gitlab-runner/.envs .
    - docker-compose -f local.yml build
    # Ensure celerybeat does not crash due to non-existent tables
    - docker-compose -f local.yml run --rm django python manage.py migrate
    - docker-compose -f local.yml up -d
  script:
    - docker-compose -f local.yml run django pytest
  tags:
    - collections
