stages:
#  - lint
  - unit_tests
  - create_merge_request
  - web_test_check # there is not need to overwrite anything in this stage
  - tag_release_check

variables:
  POSTGRES_USER: 'gfbio_collections'
  POSTGRES_PASSWORD: ''
  POSTGRES_DB: 'test_gfbio_collections'
  POSTGRES_HOST_AUTH_METHOD: trust
  CELERY_BROKER_URL: 'redis://redis:6379/0'

#flake8:
#  stage: lint
#  image: python:3.9-alpine
#  before_script:
#    - whoami
#    - pip install flake8
#    - PATH=$PATH:/home/gitlab-runner/.local/bin
#  script:
#    - flake8
#  tags:
#    - collections

pytest:
  stage: unit_tests
  image: docker/compose:latest # :1.29.2
#  services:
#    - docker:dind
  before_script:
    - PATH=$PATH:/home/gitlab-runner/.local/bin
    - whoami
#    - sudo rm -rf /home/gitlab-runner/builds/*
    - docker info
    #- rsync -a /home/gitlab-runner/.envs .
    - docker-compose -f local.yml build
    # Ensure celerybeat does not crash due to non-existent tables
    - docker-compose -f local.yml run --rm django python manage.py migrate
    - docker-compose -f local.yml up -d
  script:
    - docker-compose -f local.yml run django pytest
  tags:
    - collections
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: manual

#before_script:
#  - PATH=$PATH:/home/gitlab-runner/.local/bin
#
#include:
#  - project: gfbio/cicd
#    file:
#      - '.create_merge_request.yml'
#      - '.web-test.yml'
#      - '.tag_release.yml'
#
#
#create_merge_request:
#  tags:
#    - collections-dev
#
#tag_release_check:
#  tags:
#    - collections-dev
#
#tag_release:
#  script:
#    - rsync -a /home/gitlab-runner/.envs .
#    - docker-compose -f production.yml down
#    - docker-compose -f production.yml build
#    - docker-compose -f production.yml up -d postgres
#    - docker-compose -f production.yml run --rm postgres backup
#    - docker-compose -f production.yml run --rm django python manage.py migrate
#    - docker-compose -f production.yml run --rm django python manage.py collectstatic
#    - docker-compose -f production.yml down
#    - docker-compose -f production.yml up -d
#  environment:
#    name: production
#    url: https://collections.rdc.gfbio.dev
#  tags:
#    - collections-dev
