# Generated by Django 3.1.12 on 2021-07-13 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='owner',
        ),
    ]
