# Generated by Django 3.1.12 on 2021-07-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('collection_name', models.CharField(blank=True, default='', max_length=100)),
                ('payload', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
