# Generated by Django 3.1.12 on 2021-06-22 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('data_id', models.CharField(blank=True, default='', max_length=100)),
                ('unique_id', models.UUIDField(default=uuid.uuid4)),
                ('id_of_schema', models.CharField(blank=True, default='', max_length=100)),
                ('id_of_type', models.CharField(blank=True, default='', max_length=100)),
                ('url', models.URLField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
