# Generated by Django 3.1.12 on 2021-06-28 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataid',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataid', to=settings.AUTH_USER_MODEL),
        ),
    ]
