# Generated by Django 3.1.12 on 2021-06-30 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataid', '0002_auto_20210628_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataid',
            old_name='data_id',
            new_name='id_of_data',
        ),
        migrations.RenameField(
            model_name='dataid',
            old_name='unique_id',
            new_name='id_unique_of_data',
        ),
        migrations.RenameField(
            model_name='dataid',
            old_name='url',
            new_name='url_of_data',
        ),
    ]
