# Generated by Django 3.2.13 on 2022-07-07 08:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('set', models.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
