# Generated by Django 3.2.13 on 2022-07-13 06:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('set', models.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('external_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('origin', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
