# Generated by Django 3.2.13 on 2022-07-29 07:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_service'),
        ('collection', '0002_auto_20220728_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='origin',
        ),
        migrations.AddField(
            model_name='collection',
            name='service',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, to='users.service'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
