# Generated by Django 3.2.13 on 2023-05-12 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20220729_0730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['created'], 'permissions': (('change_collection_of_other_service', 'Can change existing collections of another service.'),)},
        ),
    ]
