# Generated by Django 3.2.9 on 2021-12-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_alter_collection_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='payload',
            field=models.JSONField(default=dict),
        ),
    ]
