# Generated by Django 3.2.9 on 2021-12-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_alter_collection_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='identificator',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collection_name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
