# Generated by Django 3.2.9 on 2021-12-07 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_auto_20211207_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='identificator',
            new_name='collection_identifier',
        ),
    ]
