# Generated by Django 3.2.9 on 2021-12-14 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_rename_payload_collection_collection_payload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='collection_identifier',
            new_name='collection_user',
        ),
    ]
