# Generated by Django 3.2.9 on 2021-12-14 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_rename_collection_identifier_collection_collection_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='collection_user',
            new_name='collection_owner',
        ),
    ]
