# Generated by Django 3.2.9 on 2021-12-14 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0008_rename_collection_user_collection_collection_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='collection_owner',
        ),
        migrations.AddField(
            model_name='collection',
            name='collection_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_collections', to=settings.AUTH_USER_MODEL),
        ),
    ]
