# Generated by Django 3.2.9 on 2021-12-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0009_auto_20211214_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collection_owner',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
