# Generated by Django 3.2.9 on 2021-12-15 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0010_collection_collection_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='collection_payload',
            new_name='payload',
        ),
    ]
