# Generated by Django 3.2.9 on 2021-12-15 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0011_rename_collection_payload_collection_payload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='payload',
            new_name='collection_payload',
        ),
    ]
