# Generated by Django 3.2.9 on 2021-12-15 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0012_rename_payload_collection_collection_payload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='collection_user',
        ),
        migrations.AddField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_collection', to=settings.AUTH_USER_MODEL),
        ),
    ]
