# Generated by Django 3.2.9 on 2021-12-15 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0013_auto_20211215_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='user',
            new_name='collection_user',
        ),
    ]
