# Generated by Django 3.2.9 on 2021-12-15 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0014_rename_user_collection_collection_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='collection_user',
        ),
    ]
