# Generated by Django 3.2.9 on 2021-12-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('collection_name', models.CharField(blank=True, max_length=128)),
                ('collection_payload', models.JSONField(default=dict)),
                ('collection_owner', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
