# Generated by Django 3.2.13 on 2022-07-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'service', 'verbose_name_plural': 'services'},
        ),
        migrations.AlterField(
            model_name='service',
            name='origin',
            field=models.CharField(blank=True, max_length=255, verbose_name='Origin'),
        ),
    ]
