# Generated by Django 3.2.13 on 2023-05-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_service_validation_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='validation_schema',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
