# Generated by Django 3.2.13 on 2022-07-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220727_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='origin',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Origin'),
        ),
    ]
